name: Publish to NPM/GPR
on:
  release:
    types: [published]
permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  publish:
    environment: deploy
    runs-on: ubuntu-latest

    name: Publish
    steps:
      - uses: actions/checkout@v6

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: NPM Install
        run: npm ci

      - name: NPM Build
        run: npm run build

      - name: Publish (NPM)
        run: npm publish --access public

      - uses: actions/setup-node@v6
        with:
          registry-url: 'https://npm.pkg.github.com'

      - name: Publish (GPR)
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
